name: RMG

on: [push, pull_request]

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Packages
        run: |
          sudo apt-get -qq update
          sudo apt-get upgrade
          sudo apt-get -y install cmake libhidapi-dev libsamplerate0-dev libminizip-dev libsdl2-dev libfreetype6-dev libgl1-mesa-dev libglu1-mesa-dev pkg-config zlib1g-dev binutils-dev libspeexdsp-dev qt5-default libqt5svg5-dev build-essential nasm git zip
      - name: Prepare Environment
        run: |
          echo "GIT_REVISION=$(git describe --tags --always)" >> $GITHUB_ENV
      - name: Build RMG (Portable)
        run: ./Source/Script/Build.sh Release
        shell: bash
      - name: Upload RMG (Portable)
        uses: actions/upload-artifact@v2
        with:
          name: RMG-Portable-Linux64-${{ env.GIT_REVISION }}
          path: Bin/Release/*

  Windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: msys2/setup-msys2@v2
        with:
          path-type: inherit
          update: true
          install: >-
            make
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-hidapi
            mingw-w64-x86_64-freetype
            mingw-w64-x86_64-libpng
            mingw-w64-x86_64-SDL2
            mingw-w64-x86_64-jasper
            mingw-w64-x86_64-qt5
            mingw-w64-x86_64-SDL2
            mingw-w64-x86_64-hidapi
            mingw-w64-x86_64-libsamplerate
            mingw-w64-x86_64-python3-pip
            mingw-w64-x86_64-python3-pyopenssl
            mingw-w64-x86_64-nasm
            git
      - name: Prepare Environment
        run: |
          $env:revision = git describe --tags --always
          echo "GIT_REVISION=$env:revision" >> $env:GITHUB_ENV
        shell: pwsh
      - name: Build RMG (Portable)
        run: ./Source/Script/Build.sh Release
        shell: msys2 {0}
      - name: Create Installer
        run: .\Build\Release\Source\Installer\CreateInstaller.bat
      - name: Upload RMG (Portable)
        uses: actions/upload-artifact@v2
        with:
          name: RMG-Portable-Windows64-${{ env.GIT_REVISION }}
          path: Bin/Release/*
      - name: Upload RMG (Installer)
        uses: actions/upload-artifact@v2
        with:
          name: RMG-Setup-Windows64-${{ env.GIT_REVISION }}
          path: Bin/*.exe
